fix: onGameResize callback #1305
flame-engine/flame pull request #1306
Opened 2022-01-08 22:55 UTC by mancj

# Description

This pull request fixes #1305.
It calls onGameResize callback when component added in _actuallyAdd method

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the
relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples`.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change. (Indicate it in the [Conventional Commit] prefix with a `!`,
  e.g. `feat!:`, `fix!:`).
- [x] No, this is *not* a breaking change.

## Related Issues

#1305 

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

2022-01-09 11:26 UTC, spydon commented
This should already be done here:
https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/game/flame_game.dart#L53

2022-01-09 11:30 UTC, mancj commented
@spydon Yes, but there is a bug in android devices at the first launch. Please read [this message](https://discord.com/channels/509714518008528896/929095243238895626/929469341940989972) from our discussion on discord.

2022-01-09 11:38 UTC, mancj commented
Maybe my solution is not the best one, because i didn't learn all the engine code, but this solves the bug.

2022-01-12 22:14 UTC, spydon requested changes
Since this will create double calls to `onGameResize` in some cases it shouldn't be done in this way, so I'll block this until we come up with another way to solve this bug (we could also close this PR if you don't have another idea of how to do it).

2022-01-17 15:35 UTC, spydon commented
I'll close this PR, but feel free to discuss more possible solutions on the issue (#1305).

2022-01-17 15:35 UTC, closed without merging