fix: removed redundant null check operator
flame-engine/flame pull request #1576
Opened 2022-04-26 11:11 UTC by alestiago

# Description

Removes using null check operator `!` where receiver can't be null.

## Checklist

- [X] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [X] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [X] I have updated/added tests for ALL new/updated/fixed functionality.
- [X] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [X] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

## Related Issues

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

2022-04-26 15:47 UTC, spydon commented
The compiler doesn't know that it can't be null, hence the `!`.
The analyzer would have complained earlier if it wasn't needed.

2022-04-27 17:14 UTC, spydon commented
Please try this with Flutter stable, I'm guessing you get these warnings because you are on the master branch.

2022-04-27 18:25 UTC, spydon requested changes
I've tried this locally on the latest stable and I don't get these analyze issues without this fix.
So this should probably be closed, and possibly re-opened when the current Flutter master reaches stable is the static analyzer have become that smart.

2022-04-28 04:37 UTC, alestiago commented
Closing and reopening when stable is reached sounds good to me.

2022-04-28 05:42 UTC, closed without merging

2022-05-17 18:50 UTC, ikbendewilliam commented
I do get the warnings on startup, why not merge this?
```
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/game/game_render_box.dart:13
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/3.0.0/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addTimingsCallback(game.onTimingsCallback);
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/game/game_render_box.dart:68
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/3.0.0/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addObserver(this);
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/game/game_render_box.dart:72
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/3.0.0/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1

    WidgetsBinding.instance!.removeObserver(this);
```

2022-05-17 18:58 UTC, spydon commented
It is merged (the PR was opened before 3.0.0 was released), but we haven't released a new version yet since we are waiting for one performance fix coming in in the coming days.

2022-05-17 19:15 UTC, ikbendewilliam commented
Ah great, that's why I couldn't find a new PR 💯