fix: Remove unnecessary autoresize parameter
flame-engine/flame pull request #3054
Opened 2024-02-28 06:37 UTC by fa-fifi

# Description

I received an assertion error after I set `autoResize` to true when I am using `SpriteComponent.fromImage` component. It's kinda weird for me that the message tells me **"If size is set, autoResize should be false or size should be null when autoResize is true.''**, but the thing is I never set the size for that image yet. Then, I check the code and I found out that the size will never be null anyway, so the `autoresize` should always false.

In this PR, I just remove the redundant autoResize parameter since you can only set it as false, otherwise it will give an assertion error. In case you have a different opinion, I open to a discussion.

## Checklist

- [ ] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] No, this PR is not a breaking change.

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

2024-02-28 08:45 UTC, spydon commented on packages/flame/lib/src/components/sprite_component.dart
>            size: size ?? srcSize ?? image.size,
What's the reason for that? Then it'll have a different behavior than the other constructor right? :thinking:

2024-02-28 09:25 UTC, ufrshubham commented on packages/flame/lib/src/components/sprite_component.dart
>            size: size ?? srcSize ?? image.size,
Not really. `SpriteComponent.fromImage` internally invokes the same constructor. 

https://github.com/flame-engine/flame/blob/e434bafb15fc486c51b43aaa9d9190b8b7e783cb/packages/flame/lib/src/components/sprite_component.dart#L69

2024-02-28 09:32 UTC, fa-fifi commented on packages/flame/lib/src/components/sprite_component.dart
>            size: size ?? srcSize ?? image.size,
So... should I commit changes based on @ufrshubham's suggestion?

2024-02-28 09:34 UTC, spydon commented on packages/flame/lib/src/components/sprite_component.dart
>            size: size ?? srcSize ?? image.size,
Yeah, please do

2024-02-28 09:34 UTC, ufrshubham commented on packages/flame/lib/src/components/sprite_component.dart
>            size: size ?? srcSize ?? image.size,
Yup, commit that change and then `autoResize` can be left as it was earlier.

2024-02-28 10:03 UTC, spydon approved these changes

2024-02-28 15:16 UTC, ufrshubham requested changes
@fa-fifi can you update the title and description of the PR to be inline with what it actually does. Also, some tests for `SpriteComponent.fromImage` would be good.

2024-02-29 16:26 UTC, ufrshubham approved these changes

2024-03-01 21:01 UTC, merged